src/HR/Controllers/ConfigurationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HR.Data;
using HR.Models;

namespace HR.Controllers
{
    public class ConfigurationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ConfigurationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Configurations
        public async Task<IActionResult> Index()
        {
            return View(await _context
                .Configuration
                .OrderBy(o => o.ContractType)
                .ThenBy(o => o.ExperienceFrom)
                .ThenBy(o => o.ExperienceTo)
                .ToListAsync());
        }


        // GET: Configurations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Configurations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ContractType,ExperienceFrom,ExperienceTo,MinimalSalary")] Configuration configuration)
        {
            if (ModelState.IsValid)
            {
                _context.Add(configuration);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(configuration);
        }

        // GET: Configurations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var configuration = await _context.Configuration.SingleOrDefaultAsync(m => m.Id == id);
            if (configuration == null)
            {
                return NotFound();
            }
            return View(configuration);
        }

        // POST: Configurations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ContractType,ExperienceFrom,ExperienceTo,MinimalSalary")] Configuration configuration)
        {
            if (id != configuration.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(configuration);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConfigurationExists(configuration.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(configuration);
        }

        // GET: Configurations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var configuration = await _context.Configuration.SingleOrDefaultAsync(m => m.Id == id);
            if (configuration == null)
            {
                return NotFound();
            }

            return View(configuration);
        }

        // POST: Configurations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var configuration = await _context.Configuration.SingleOrDefaultAsync(m => m.Id == id);
            _context.Configuration.Remove(configuration);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ConfigurationExists(int id)
        {
            return _context.Configuration.Any(e => e.Id == id);
        }
    }
}

src/HR/Controllers/ContractsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HR.Data;
using HR.Models;
using HR.Models.ContractViewModels;
using HR.Interface.Enums;
using HR.Interface;
using HR.Interface.Dto;
using HR.Services;

namespace HR.Controllers
{
    public class ContractsController : Controller
    {
        public const int EXPENSIVE_CONTRACT_LIMIT = 5000;
        public const int EXPERIENCED_PROGRAMMER_LIMIT = 5;
        public const int PAGE_SIZE = 10;

        private readonly ApplicationDbContext _context;
        private readonly IContractCalculator _contractCalculator;

        public ContractsController(ApplicationDbContext context, ContractCalculatorService contractCalculator)
        {
            _context = context;
            _contractCalculator = contractCalculator;
        }

        // GET: Contracts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contracts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ContractType,Experience,Name")] Contract contract)
        {
            _appendSalary(contract);

            if (ModelState.IsValid)
            {
                _context.Add(contract);
                await _context.SaveChangesAsync();
                return RedirectToAction("Filter");
            }

            return View(contract);
        }

        // GET: Contracts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract.SingleOrDefaultAsync(m => m.Id == id);

            _appendSalary(contract);

            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // POST: Contracts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ContractType,Experience,Name")] Contract contract)
        {
            if (id != contract.Id)
            {
                return NotFound();
            }

            _appendSalary(contract);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contract);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContractExists(contract.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Filter");
            }

            return View(contract);
        }

        // GET: Contracts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract.SingleOrDefaultAsync(m => m.Id == id);

            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // POST: Contracts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contract = await _context.Contract.SingleOrDefaultAsync(m => m.Id == id);
            _context.Contract.Remove(contract);
            await _context.SaveChangesAsync();
            return RedirectToAction("Filter");
        }

        private bool ContractExists(int id)
        {
            return _context.Contract.Any(e => e.Id == id);
        }

        // GET: Contracts/Evaluate/
        public IActionResult Evaluate(int contractType, int experience)
        {
            var salary = _contractCalculator.CalculateSalary((ContractType)contractType, experience);

            return Json(new { salary = salary });
        }

        // GET: Contracts/Filter/
        [HttpGet]
        public IActionResult Filter()
        {
            var contracts = _context.Contract.OrderBy(o => o.Name).AsQueryable();
            var viewModel = new FilterViewModel();
            contracts = _paginate(contracts, viewModel);
            viewModel.Contracts = contracts.ToList();

            return View(viewModel);
        }

        // POST: Contracts/Filter/
        [HttpPost]
        public IActionResult Filter(FilterViewModel viewModel)
        {
            var contracts = _appendFilters(viewModel, _context.Contract.OrderBy(o => o.Name));
            contracts = _paginate(contracts, viewModel);
            viewModel.Contracts = contracts.ToList();

            return View(viewModel);
        }

        #region private

        private IQueryable<Contract> _paginate(IQueryable<Contract> contract, FilterViewModel viewModel)
        {
            viewModel.PageCount = (int)Math.Ceiling(contract.Count() / (decimal)PAGE_SIZE);
            viewModel.Page = Math.Min(viewModel.Page, viewModel.PageCount);

            var skip = (viewModel.Page - 1) * PAGE_SIZE;

            return contract
                .Skip(skip)
                .Take(PAGE_SIZE);
        }

        private void _appendSalary(Contract contract)
        {

            contract.Salary = _contractCalculator.CalculateSalary(contract.ContractType, contract.Experience);
        }

        private static IQueryable<Contract> _appendFilters(FilterViewModel viewModel, IQueryable<HR.Models.Contract> contracts)
        {
            var ret = contracts;

            ret = _appendNameFilter(viewModel, contracts);
            ret = _appendContractTypeFilter(viewModel, contracts, ret);
            ret = _appendExperienceFilters(viewModel, contracts, ret);
            ret = _appendSalaryFilters(viewModel, contracts, ret);
            ret = _appendAdditionalFilters(viewModel, ret);

            return ret;
        }

        private static IQueryable<Contract> _appendNameFilter(FilterViewModel viewModel, IQueryable<Contract> contracts)
        {
            var ret = contracts;

            if (viewModel.FilterName != null)
            {
                ret = contracts.Where(c => c.Name.IndexOf(viewModel.FilterName, StringComparison.InvariantCultureIgnoreCase) >= 0);
            }

            return ret;
        }

        private static IQueryable<Contract> _appendContractTypeFilter(FilterViewModel viewModel, IQueryable<Contract> contracts, IQueryable<Contract> ret)
        {
            if (viewModel.FilterContractType != null)
            {
                ret = contracts.Where(c => c.ContractType == viewModel.FilterContractType.Value);
            }

            return ret;
        }

        private static IQueryable<Contract> _appendExperienceFilters(FilterViewModel viewModel, IQueryable<Contract> contracts, IQueryable<Contract> ret)
        {
            if (viewModel.FilterExperienceMin > 0)
            {
                ret = contracts.Where(c => c.Experience >= viewModel.FilterExperienceMin);
            }

            if (viewModel.FilterExperienceMax > 0)
            {
                ret.Where(c => c.Experience <= viewModel.FilterExperienceMin);
            }

            return ret;
        }

        private static IQueryable<Contract> _appendSalaryFilters(FilterViewModel viewModel, IQueryable<Contract> contracts, IQueryable<Contract> ret)
        {
            if (viewModel.FilterSalaryMin > 0)
            {
                ret = contracts.Where(c => c.Salary >= viewModel.FilterSalaryMin);
            }

            if (viewModel.FilterSalaryMax > 0)
            {
                ret = ret.Where(c => c.Salary <= viewModel.FilterSalaryMin);
            }

            return ret;
        }

        private static IQueryable<Contract> _appendAdditionalFilters(FilterViewModel viewModel, IQueryable<Contract> ret)
        {
            if (viewModel.FilterExpensiveContracts)
            {
                ret = ret.Where(c => c.Salary > EXPENSIVE_CONTRACT_LIMIT);
            }

            if (viewModel.FilterExperiencedProgrammers)
            {
                ret = ret.Where(c =>
                    c.Experience >= EXPERIENCED_PROGRAMMER_LIMIT
                    && c.ContractType == ContractType.Programmer);
            }

            return ret;
        }

        #endregion private
    }
}

src/HR/Controllers/FactorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HR.Data;
using HR.Models;

namespace HR.Controllers
{
    public class FactorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FactorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Factors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Factor.ToListAsync());
        }

        // GET: Factors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var factor = await _context.Factor.SingleOrDefaultAsync(m => m.Id == id);
            if (factor == null)
            {
                return NotFound();
            }
            return View(factor);
        }

        // POST: Factors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ContractType,FactorA,FactorB")] Factor factor)
        {
            if (id != factor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(factor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FactorExists(factor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(factor);
        }

        private bool FactorExists(int id)
        {
            return _context.Factor.Any(e => e.Id == id);
        }
    }
}

src/HR/Views/Shared/_FactorInfoPartial.cshtml
<div class="alert alert-success" role="alert">
    Salary is calculated by following formula:<br>

    <h3>
        <span class="label label-success label-lg">Minimal Salary</span>
        + <span class="label label-success label-lg">Experience * FactorA</span>
        + <span class="label label-success label-lg">Minimal Salary * FactorB</span>
    </h3>
    <br/>
    Where <b>factor A</b> and <b>Factor B</b> are <a asp-action="Index", asp-controller="Factors">configurable</a> values for every job.
</div>

src/HR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">HR</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Contracts" asp-action="Filter">Contracts</a></li>
                    <li><a asp-area="" asp-controller="Configurations" asp-action="Index">Policy configuration</a></li>
                    <li><a asp-area="" asp-controller="Factors" asp-action="Index">Factors configuration</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://przybyla.info">2016 - HR - Krystian Przybyła</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/PaginationHelper.js" asp-append-version="true"></script>
        <script src="~/js/SalaryHelper.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/PaginationHelper.min.js" asp-append-version="true"></script>
        <script src="~/js/SalaryHelper.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>